on:
  workflow_dispatch:

jobs:
  # run-checks:
  #   name: "Lint Code"
  #   uses: ./.github/checks/lint.yml


  build-base-images:
    name: "Build Base Images"
    # needs: run-checks
    uses: ./.github/workflows/multi-arch-build.yml
    with:
      PUSH: true
      TARGET: "ignition-base"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  
  build-iiot-images:
    name: "Build IIOT Images"
    # needs: run-checks
    uses: ./.github/workflows/multi-arch-build.yml
    with:
      PUSH: true
      TARGET: "ignition-iiot"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  
  build-mes-images:
    name: "Build MES Images"
    # needs: run-checks
    uses: ./.github/workflows/multi-arch-build.yml
    with:
      PUSH: true
      TARGET: "ignition-mes"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}