name: "Multibuild"

on:
  workflow_call:
    inputs:
      PUSH: 
        description: "Push to Docker Hub"
        required: false
        default: false
        type: boolean
      TARGET:
        description: "Target Group"
        required: false
        default: "build"
        type: string
    secrets:
      DOCKER_USERNAME:
        description: "Docker Hub username"
        required: true
      DOCKER_ACCESS_TOKEN:
        description: "Docker Hub access token"
        required: true

jobs:
  build:
    name: Setup

    runs-on: ubuntu-latest-8-cores
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: QEMU Setups
        id: qemu
        uses: docker/setup-qemu-action@v2.1.0
        with:
          image: tonistiigi/binfmt:qemu-v6.2.0
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - 
        name: Buildx Setup
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - 
        name: Build
        uses: docker/bake-action@v2.3.0
        with:
          files: ./docker-bake.hcl
          targets: ${{ inputs.TARGET }}
          push: ${{ inputs.PUSH }}